PERSISTENT = "PERSISTENT"
SERVICE_CYCLE = "SERVICE_CYCLE"
SESSION = "SESSION"


MATCHING_POLICIES = {

    # Examination
    "HALL_ALLOCATION": SESSION,
    "TIMETABLE_ISSUE": SESSION,
    "INVIGILATOR_UNAVAILABLE": SESSION,
    "SEATING_ISSUE": SESSION,
    "EXAM_RESOURCE_ISSUE": SESSION,

    # Academic Administration
    "NO_TEACHER_ASSIGNED": SESSION,
    "NO_SUBSTITUTE": SESSION,
    "CLASS_CONFLICT": SESSION,
    "FACULTY_TIMETABLE_ISSUE": SESSION,
    "OTHER_ACADEMIC_ISSUE": SESSION,

    # Maintenance
    "ELECTRICAL": PERSISTENT,
    "PLUMBING": PERSISTENT,
    "FURNITURE": PERSISTENT,
    "CLASSROOM_EQUIPMENT": PERSISTENT,
    "INFRASTRUCTURE_DAMAGE": PERSISTENT,

    # Sanitation
    "CLEANING": SERVICE_CYCLE,
    "WASTE": SERVICE_CYCLE,
    "WASHROOM": SERVICE_CYCLE,
    "WATER_SANITATION": SERVICE_CYCLE,

    # IT
    "NETWORK": PERSISTENT,
    "COMPUTER": PERSISTENT,
    "PROJECTOR": PERSISTENT,
    "SMART_CLASSROOM": PERSISTENT,
    "OTHER_IT_ISSUE": PERSISTENT,

    # Security
    "SUSPICIOUS_ACTIVITY": SESSION,
    "UNAUTHORIZED_ACCESS": SESSION,
    "SAFETY_HAZARD": PERSISTENT,
    "SECURITY_EQUIPMENT": PERSISTENT,

    # Administration
    "ADMINISTRATIVE_SERVICE": SERVICE_CYCLE,
    "FACILITY_RESOURCE": PERSISTENT,
    "OTHER_ADMINISTRATIVE_ISSUE": SERVICE_CYCLE,
}


DEFAULT_POLICY = PERSISTENT


def get_matching_policy(subcategory: str) -> str:
    if not subcategory or not subcategory.strip():
        raise ValueError("Subcategory is required.")

    return MATCHING_POLICIES.get(
        subcategory.upper().strip(),
        DEFAULT_POLICY,
    )